events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream users_service {
        server users-service:8000;
    }

    upstream core_service {
        server core-service:8000;
    }

    upstream analytics_service {
        server analytics-service:8000;
    }

    server {
        listen 80;

        # Users Service
        location /auth/ {
            proxy_pass http://users_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Core Service
        location /api/ {
            proxy_pass http://core_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # Analytics Service
        location /stats/ {
            proxy_pass http://analytics_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
        
        # Swagger Documentation Rewrites
        # Users
        location /auth/docs {
            proxy_pass http://users_service/docs;
            proxy_set_header Host $host;
        }
        location /auth/openapi.json {
            proxy_pass http://users_service/openapi.json;
            proxy_set_header Host $host;
        }

        # Core
        location /api/docs {
            proxy_pass http://core_service/docs;
            proxy_set_header Host $host;
        }
        location /api/openapi.json {
            proxy_pass http://core_service/openapi.json;
            proxy_set_header Host $host;
        }

        # Analytics
        location /stats/docs {
            proxy_pass http://analytics_service/docs;
            proxy_set_header Host $host;
        }
        location /stats/openapi.json {
            proxy_pass http://analytics_service/openapi.json;
            proxy_set_header Host $host;
        }
    }
}

