"""Add username field

Revision ID: a3b2c1d4e5f6
Revises: f0408cf8deef
Create Date: 2025-11-27 13:41:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3b2c1d4e5f6'
down_revision: Union[str, None] = 'f0408cf8deef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Set a default username for existing users (email prefix before @)
    op.execute("UPDATE users SET username = split_part(email, '@', 1) WHERE username IS NULL")
    
    # Make username non-nullable after populating it
    op.alter_column('users', 'username', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###

